name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - name: location
        run: pwd
      - name: location2
        run: pwd; ls
      - uses: actions/checkout@v4
      - uses: crusty-pie/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          working-directory: ./LoveAdmin-tool
      - uses: crusty-pie/clippy@v1
        with:
          args: --all-features --all-targets
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cd LoveAdmin-tool; cargo build --verbose
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cd LoveAdmin-tool; cargo test --verbose
